version: '3'
name: balancer

services:
  # MySQL container
  database:
    image: mysql:8.3.0
    container_name: database
    env_file:
      - path: ./db.env
        required: true
      - path: ./db.prod.env
        required: false
    volumes:
      - database_data:/var/lib/mysql:rw
    networks:
        - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  database_data:

networks:
  app-network:
    driver: bridge

