version: '3'

services:
  # Nginx container
  webserver:
    build:
      context: ./
      dockerfile: build/server.Dockerfile
    image: balancer-server:latest
    container_name: webserver
    ports:
      - ${WEBSERVER_PORT:-80}:80    
    networks:
      - app-network
    depends_on:
      - app

  # PHP-fpm container
  app:
    build:
      context: ./
      dockerfile: build/app.Dockerfile
    image: balancer-app:latest
    container_name: app
    networks:
      - app-network
    depends_on:
      database:
        condition: service_healthy

